//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 
namespace Kontur.Recognition.SpreadSheetModel.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kontur.ru/export/table")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://kontur.ru/export/table", IsNullable=false)]
    public partial class Table {
        
        private NumberFormats numberFormatsField;
        
        private Cell[] cellField;
        
        private int startRowField;
        
        private int endRowField;
        
        private int startColField;
        
        private int endColField;
        
        /// <remarks/>
        public NumberFormats NumberFormats {
            get {
                return this.numberFormatsField;
            }
            set {
                this.numberFormatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cell")]
        public Cell[] Cell {
            get {
                return this.cellField;
            }
            set {
                this.cellField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int startRow {
            get {
                return this.startRowField;
            }
            set {
                this.startRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int endRow {
            get {
                return this.endRowField;
            }
            set {
                this.endRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int startCol {
            get {
                return this.startColField;
            }
            set {
                this.startColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int endCol {
            get {
                return this.endColField;
            }
            set {
                this.endColField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kontur.ru/export/table")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://kontur.ru/export/table", IsNullable=false)]
    public partial class NumberFormats {
        
        private CellFormat[] cellFormatField;
        
        private System.DateTime nullDateField;
        
        private int defaultDecimalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CellFormat")]
        public CellFormat[] CellFormat {
            get {
                return this.cellFormatField;
            }
            set {
                this.cellFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime nullDate {
            get {
                return this.nullDateField;
            }
            set {
                this.nullDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int defaultDecimals {
            get {
                return this.defaultDecimalsField;
            }
            set {
                this.defaultDecimalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kontur.ru/export/table")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://kontur.ru/export/table", IsNullable=false)]
    public partial class CellFormat {
        
        private int idField;
        
        private int typeField;
        
        private string formatStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formatString {
            get {
                return this.formatStringField;
            }
            set {
                this.formatStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kontur.ru/export/table")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://kontur.ru/export/table", IsNullable=false)]
    public partial class Cell {
        
        private int rowField;
        
        private int colField;
        
        private double rawValueField;
        
        private int formatIdField;
        
        private CellContentType contentTypeField;
        
        private int xMinField;
        
        private int yMinField;
        
        private int xMaxField;
        
        private int yMaxField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double rawValue {
            get {
                return this.rawValueField;
            }
            set {
                this.rawValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int formatId {
            get {
                return this.formatIdField;
            }
            set {
                this.formatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CellContentType contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int xMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int yMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int xMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int yMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kontur.ru/export/table")]
    public enum CellContentType {
        
        /// <remarks/>
        empty,
        
        /// <remarks/>
        value,
        
        /// <remarks/>
        text,
    }
}
